# Generated by Django 4.0.2 on 2022-02-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WS_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='Время события')),
                ('username', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
