# Generated by Django 4.0.2 on 2022-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0002_rename_ws_model_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='ws',
            name='app',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
