# Generated by Django 4.0.2 on 2022-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название страницы'),
        ),
    ]
