# Generated by Django 4.0.2 on 2022-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_alter_page_date_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
